type: preprocessor
tune_mode: params
pipeline:
- type: filter.gene
  target: FilterGenesPercentile
  params_to_tune:
    min_val:
      min: 1
      max: 10
    max_val:
      min: 95
      max: 99
    mode:
      values:
      - sum
      - var
      - cv
      - rv
- type: filter.cell
  target: FilterCellsPlaceHolder
- type: normalize
  target: ScTransform
  params_to_tune:
    min_cells:
      min: 1
      max: 10
    gmean_eps:
      min: 1
      max: 10
    n_genes:
      min: 1000
      max: 3000
    n_cells:
      values:
      - null
      - 1
      - 10
      - 100
    bin_size:
      min: 300
      max: 800
    bw_adjust:
      min: 1.0
      max: 5.0
  params:
    processes_num: 8
- type: filter.gene
  target: HighlyVariableGenesLogarithmizedByTopGenes
  params_to_tune:
    n_top_genes:
      min: 100
      max: 10000
    n_bins:
      min: 10
      max: 30
    flavor:
      values:
      - seurat
      - cell_ranger
- type: feature.cell
  target: WeightedFeatureSVD
  params:
    out: feature.cell
  params_to_tune:
    n_components:
      min: 0.8
      max: 0.95
    feat_norm_mode:
      values:
      - null
      - normalize
      - standardize
      - minmax
      - l2
- type: graph.cell
  target: CellFeatureGraph
  params:
    cell_feature_channel: feature.cell
- type: misc
  target: SetConfig
  params:
    config_dict:
      feature_channel: CellFeatureGraph
      feature_channel_type: uns
      label_channel: Group
wandb:
  entity: xzy11632
  project: dance-dev
  method: bayes
  metric:
    name: acc
    goal: maximize
